// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLkZRub8ah9rDxviiPeta8O9iPN23VB98',
    appId: '1:508994496732:web:3e7de2fbaccd6c1ea1ac19',
    messagingSenderId: '508994496732',
    projectId: 'spotify-flutter-clone-app-2025',
    authDomain: 'spotify-flutter-clone-app-2025.firebaseapp.com',
    storageBucket: 'spotify-flutter-clone-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhne2BhFjs84I4cKpSErCpVBkmJ8TPthc',
    appId: '1:508994496732:android:91331122d107f197a1ac19',
    messagingSenderId: '508994496732',
    projectId: 'spotify-flutter-clone-app-2025',
    storageBucket: 'spotify-flutter-clone-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlt3ZMXCJWeCPVnbmTodRHHk3LR5YXAs',
    appId: '1:508994496732:ios:26a3abf67c5b201aa1ac19',
    messagingSenderId: '508994496732',
    projectId: 'spotify-flutter-clone-app-2025',
    storageBucket: 'spotify-flutter-clone-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.spotifyFutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlt3ZMXCJWeCPVnbmTodRHHk3LR5YXAs',
    appId: '1:508994496732:ios:26a3abf67c5b201aa1ac19',
    messagingSenderId: '508994496732',
    projectId: 'spotify-flutter-clone-app-2025',
    storageBucket: 'spotify-flutter-clone-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.spotifyFutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLkZRub8ah9rDxviiPeta8O9iPN23VB98',
    appId: '1:508994496732:web:089b3e6845071781a1ac19',
    messagingSenderId: '508994496732',
    projectId: 'spotify-flutter-clone-app-2025',
    authDomain: 'spotify-flutter-clone-app-2025.firebaseapp.com',
    storageBucket: 'spotify-flutter-clone-app-2025.firebasestorage.app',
  );
}
